// generateConfigs.js
import { writeFileSync } from "fs";

const amplifyConfig = {
  aws_project_region: process.env.AWS_PROJECT_REGION,
  aws_cloud_logic_custom: [
    {
      name: "NoiseAppAPI",
      endpoint: process.env.API_ENDPOINT,
      region: process.env.AWS_PROJECT_REGION,
    },
  ],
  aws_cognito_identity_pool_id: process.env.AWS_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: process.env.AWS_PROJECT_REGION,
  aws_user_pools_id: process.env.AWS_USER_POOLS_ID,
  aws_user_pools_web_client_id: process.env.AWS_USER_POOLS_WEB_CLIENT_ID,
  oauth: {
    domain: process.env.OAUTH_DOMAIN,
  },
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_UPPERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_dynamodb_all_tables_region: process.env.AWS_PROJECT_REGION,
  aws_dynamodb_table_schemas: [
    {
      tableName: "NoiseDataByUser-dev",
      region: process.env.AWS_PROJECT_REGION,
    },
  ],
};

// Generate amplifyconfiguration.json
writeFileSync(
  "./src/amplifyconfiguration.json",
  JSON.stringify(amplifyConfig, null, 2)
);

// Generate aws-exports.js
const awsExportsContent = `/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = ${JSON.stringify(amplifyConfig, null, 2)};

export default awsmobile;`;

writeFileSync("./src/aws-exports.js", awsExportsContent);

console.log("Configuration files generated successfully.");
